export const GET_ALL_DATA_START = "GET_ALL_DATA_START";
export const GET_ALL_DATA_SUCCESS = "GET_ALL_DATA_SUCCESS";
export const GET_ALL_DATA_FAILED = "GET_ALL_DATA_FAILED";

export const ADD_NEW_PRODUCT_START = "ADD_NEW_PRODUCT_START";
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";
export const ADD_NEW_PRODUCT_FAILED = "ADD_NEW_PRODUCT_FAILED";

//
export const IS_LOADING = "IS_LOADING";