export const GET_ALL_DATA_START = "GET_ALL_DATA_START";
export const GET_ALL_DATA_SUCCESS = "GET_ALL_DATA_SUCCESS";
export const GET_ALL_DATA_FAILED = "GET_ALL_DATA_FAILED";

//add new product
export const ADD_NEW_PRODUCT_START = "ADD_NEW_PRODUCT_START";
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";
export const ADD_NEW_PRODUCT_FAILED = "ADD_NEW_PRODUCT_FAILED";

//delete product
export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

//ADMIN LOGIn
export const ADMIN_LOGIN_START = "ADMIN_LOGIN_START";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILED = "ADMIN_LOGIN_FAILED";

//ADMIN LOGOUT
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

//
export const ADMIN_IS_LOADING = "ADMIN_IS_LOADING";
