export const GET_ALL_DATA_START = "GET_ALL_DATA_START";
export const GET_ALL_DATA_SUCCESS = "GET_ALL_DATA_SUCCESS";
export const GET_ALL_DATA_FAILED = "GET_ALL_DATA_FAILED";

//add new product
export const ADD_NEW_PRODUCT_START = "ADD_NEW_PRODUCT_START";
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";
export const ADD_NEW_PRODUCT_FAILED = "ADD_NEW_PRODUCT_FAILED";

//delete product
export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

//
export const ADMIN_IS_LOADING = "ADMIN_IS_LOADING";