//fetching single product
export const FETCH_SINGLE_PRODUCT_START = "FETCH_SINGLE_PRODUCT_START";
export const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS";
export const FETCH_SINGLE_PRODUCT_FAILED = "FETCH_SINGLE_PRODUCT_FAILED";

//fetching  product for home page
export const FETCH_HOME_PRODUCTS_START = "FETCH_HOME_PRODUCTS_START";
export const FETCH_HOME_PRODUCTS_SUCCESS = "FETCH_HOME_PRODUCTS_SUCCESS";
export const FETCH_HOME_PRODUCTS_FAILED = "FETCH_HOME_PRODUCTS_FAILED";

//fetching all product
export const FETCH_ALL_PRODUCTS_START = "FETCH_ALL_PRODUCTS_START";
export const FETCH_ALL_PRODUCTS_SUCCESS = "FETCH_ALL_PRODUCTS_SUCCESS";
export const FETCH_ALL_PRODUCTS_FAILED = "FETCH_ALL_PRODUCTS_FAILED";

//adding product into cart
export const ADD_PRODUCT_IN_CART = "ADD_PRODUCT_IN_CART";

//checkout start
export const CHECKOUT_START ="CHECKOUT_START";
export const CHECKOUT_SUCCESS ="CHECKOUT_SUCCESS";
export const CHECKOUT_FAILED ="CHECKOUT_FAILED";

//house keeping stuff
export const PRODUCTS_IS_LOADING = "IS_LOADING";
