//LOGIN
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

//SINGUP
export const SINGUP_START = "SINGUP_START";
export const SINGUP_SUCCESS = "SINGUP_SUCCESS";
export const SINGUP_FAILED = "SINGUP_FAILED";

//LOGOUT START
export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESSFULL = "LOGOUT_SUCCESSFULL";


//house keeping stuff
export const USER_IS_LOADING = "USER_IS_LOADING";